[language]
title = "Classes:"
of = "of"
alternatives = "Alternatives"
description = "Description"

[general]
period = "2023-2024 Genap"
person = "Moch. Nafkhan Alzamzami, S.T., M.T."
weekdays = ["Mon", "Tue", "Wed", "Thu", "Fri"]

[[general.times]]
start = "07:00"

[[general.times]]
start = "08:00"

[[general.times]]
start = "09:00"

[[general.times]]
start = "10:00"

[[general.times]]
start = "11:00"

[[general.times]]
start = "12:00"

[[general.times]]
start = "13:30"

[[general.times]]
start = "14:30"

[[general.times]]
start = "15:30"

[[general.times]]
start = "16:30"

[[general.times]]
display = "Evening"
start = "17:20"
end = "21:00"
show-time = true

[defaults]
duration = "00:50"
show-time = true

[[description]]
id = "name"
title = "Course name"

[[description]]
id = "info"
title = "Add. info"
type = "content"

[[description]]
id = "url"
title = "Website"
type = "link"

# main section defining the courses
[courses."Ana I"]
name = "Analysis I"
url = "https://en.wikipedia.org/wiki/Mathematical_analysis"
events.VL = [
  { day = "Mon", end = "12:00", room = "big room 1", priority = 5 },
  { day = "Tue", end = "12:00", room = "big room 2" }
]
events.UE = [{ day = "Fri", end = "16:00", room = "small room 5" }]

[courses."LinA I"]
name = "Linear Algebra I"
info = "#box(fill: red, inset: 2pt)[required]"
url = "https://en.wikipedia.org/wiki/Linear_algebra"
events.VL = [
  { day = "Mon", start = "16:00", room = "online" },
  { day = "Tue", start = "16:00", room = "online" }
]
events.UE = [{ day = "Mon", start = "10:00", room = "small room 1" }]

[courses."Alg I"]
name = "Algebra I"
url = "https://en.wikipedia.org/wiki/Algebra"
events.VL = [
  { day = "Tue", start = "12:00", room = "?" },
  { day = "Wed", start = "12:00", room = "big room 1" }
]
events.UE = [{ day = "Wed", start = "14:00", room = "small room 2" }]

[courses.Stoch]
name = "Stochastic"
url = "https://en.wikipedia.org/wiki/Stochastic"
color = "yellow"
events.SEM = [{ day = "Thu", start = "14:00", room = "small room 2" }]

[courses."Geo I"]
name = "Geometry I"
url = "https://en.wikipedia.org/wiki/Geometry"
priority = 3

[[courses."Geo I".events.VL]]
day = "Tue"
start = "10:00"
room = "small room 5"

[courses.Hacking]
hide = true

[courses.Sport]
hide-description = true
color = "lime"

[[courses.Sport.events."ğŸ’ƒ"]]
day = "Mon"
start = "18:00"
end = "19:30"
room = "pretty place"

[[courses.Sport.events."ğŸ’ª"]]
day = "Tue"
start = "18:30"
end = "19:30"
room = "fancy place"

[[courses.Sport.events.""]]
day = "Thu"
start = "18:30"
end = "19:30"
room = "fancy place"
hide = true

[[courses.Sport.events."ğŸŠ"]]
day = "Fri"
start = "18:30"
end = "19:30"
room = ""

[courses.Work]
color = "gray"
hide-description = true

[[courses.Work.events.""]]
day = "Mon"
start = "12:00"
end = "16:00"
room = "Office"

[[courses.Work.events.""]]
day = "Thu"
start = "08:00"
end = "14:00"
room = "Home Office"

[[courses.Work.events.""]]
day = "Fri"
start = "08:00"
end = "14:00"
room = "Home Office"
